### ISSUE TITLE
IDF-SDK 5.1 cant compile

### ISSUE THREAD

**Issue by MartinRaSt** [Seeed-Solution/SenseCAP_Indicator_ESP32#18]
Hi,
Can you make a source for compilation under the 5.1 version od IDF-SDK?
There is a problem with "hack", which cant be applied.
Thank you

**Comment by kheek** [comment]
I think I have same issue: screen is flickering fast after flash.

**Comment by Wvirgil123** [comment]
> 

Some demos must open SRAM 120M DDR feature  to compile. For ESP-IDF release/v5.1, there is no need to patch, but additional configuration is required.

[CONFIG_IDF_EXPERIMENTAL_FEATURES](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/kconfig.html#config-idf-experimental-features) is enabled
CONFIG_SPIRAM_SPEED_120M  is enabled

see [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/flash_psram_config.html#all-supported-modes-and-speeds) for more details.

**Comment by Wvirgil123** [comment]
> Hi, Can you make a source for compilation under the 5.1 version od IDF-SDK? There is a problem with "hack", which cant be applied. Thank you

Some demos must open SRAM 120M DDR feature to compile. For ESP-IDF release/v5.1, there is no need to patch, but additional configuration is required.

[CONFIG_IDF_EXPERIMENTAL_FEATURES](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/kconfig.html#config-idf-experimental-features) is enabled
CONFIG_SPIRAM_SPEED_120M is enabled

see [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/flash_psram_config.html#all-supported-modes-and-speeds) for more details.

**Comment by Wvirgil123** [comment]
> I think I have same issue: screen is flickering fast after flash.

Will the device still be flickering fast if it is left for a period of time?
