### ISSUE TITLE
Patch release5.0_psram_octal_120m.patch fail

### ISSUE THREAD

**Issue by dspkid2023** [Seeed-Solution/SenseCAP_Indicator_ESP32#19]
git apply --whitespace=fix ../patch//release5.0_psram_octal_120m.patch
error: patch failed: components/spi_flash/spi_flash_timing_tuning.c:230

**Comment by Love4yzp** [comment]
Could you please specify which IDF version you are working with? 

As for the scripts under the "tool" directory, they are available for use once you have activated the ESP-IDF environment. If you have successfully activated the environment, you should be able to run the scripts without any issues.

Please provide more details, and I'll do my best to assist you further!

**Comment by dspkid2023** [comment]
Dear Sir,

Current IDF version is 5.0.3-dirty
Only v5.0.3 I can get from GitHub base on v5.0.

Thanks for helping.

Best regards,
dspkid

mooonight ***@***.***>於 2023年8月6日 週日，09:48寫道：

**Comment by dspkid2023** [comment]
Dear Sir,

***@***.*** esp-idf % idf.py --version
/Users/ha/esp/esp-idf/tools/check_python_dependencies.py:12:
DeprecationWarning: pkg_resources is deprecated as an API. See
https://setuptools.pypa.io/en/latest/pkg_resources.html
import pkg_resources
ESP-IDF v5.0.3-dirty
***@***.*** esp-idf % git apply --whitespace=fix
../patch/release5.0_psram_octal_120m.patch
warning: components/esp_hw_support/port/esp32s3/rtc_clk.c has type 100755,
expected 100644
warning: components/esp_psram/esp32s3/Kconfig.spiram has type 100755,
expected 100644
warning: components/hal/esp32s3/include/hal/spimem_flash_ll.h has type
100755, expected 100644
warning: components/spi_flash/esp32s3/mspi_timing_tuning_configs.h has type
100755, expected 100644
warning: components/spi_flash/esp32s3/spi_timing_config.c has type 100755,
expected 100644
warning: components/spi_flash/esp32s3/spi_timing_config.h has type 100755,
expected 100644
warning: components/spi_flash/spi_flash_timing_tuning.c has type 100755,
expected 100644
error: patch failed: components/spi_flash/spi_flash_timing_tuning.c:230
error: components/spi_flash/spi_flash_timing_tuning.c: patch does not apply

Best regards,
dspkid

**Comment by dspkid2023** [comment]
Patch issue solved after pulling Tag v5.0 from github.
build and flash ok.

Thanks

**Comment by Love4yzp** [comment]
It's great to hear that the patch issue has been successfully resolved by pulling Tag v5.0 from GitHub and confirming that the build and flash are working fine.

If you have any more questions or need further assistance, please don't hesitate to reach out.
