### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by DomMonte** [Seeed-Solution/SenseCAP_Indicator_ESP32#21]
I was finally able to install the patch after much trouble but now I am getting this error: 

` error: #error "MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT defined, but not all prerequisites"
  904 | #error "MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT defined, but not all prerequisites"`

I am trying to flash indicator_ha but nothing I do seems to work.

Please help

**Comment by DomMonte** [comment]
I am using release/v5.0. I have deleted IDF and reinstalled. Also have deleted sdkconfig

**Comment by Love4yzp** [comment]
what is your OS system?
Is the IDF Virtual(not in the system global path)?
Have you modified the projection before?

**Comment by DomMonte** [comment]
I am running on Windows, IDF is installed through Visual Studio Code. Nothing has been modified

**Comment by Love4yzp** [comment]
> I am running on Windows, IDF is installed through Visual Studio Code. Nothing has been modified

Could you compile it again and give the whole compile log?

**Comment by Love4yzp** [comment]
I believe I've identified the issue. It appears that the problem might stem from the installation process of the IDF through the ESP-IDF plugin on VSCode. This could potentially result in an incomplete IDF toolchain. To rectify this, you can attempt to resolve the situation by executing the following command: 

```bash
git submodule update --init --recursive
```

Running this command will facilitate the download of any lacking submodules, which could potentially address the problem you're encountering.

**Comment by DomMonte** [comment]
Ah thank you so much for your help! I should've read the log properly at the top, I was too busy looking at the error message!
