### ISSUE TITLE
Still get static_assert about "FLASH and PSRAM Mode” even with patch applied

### ISSUE THREAD

**Issue by snej** [Seeed-Solution/SenseCAP_Indicator_ESP32#26]
When I try to build the indicator_basis example, I get a compile error `static assertion failed: "FLASH and PSRAM Mode configuration are not supported`. This happens **even after installing the IDF patch**, unlike #2. 

I have built most of the other examples successfully; only this one fails. It’s odd that I can build the `indicator_ha` demo since it’s based on this one, but there are quite a few diffs between their `sdkconfig` files, mostly having to do with SPIRAM.

```
In file included from /Users/snej/Projects/Embedded/esp-idf/components/spi_flash/esp32s3/spi_timing_config.c:15:
/Users/snej/Projects/Embedded/esp-idf/components/spi_flash/esp32s3/spi_timing_config.h:179:1: error: static assertion failed: "FLASH and PSRAM Mode configuration are not supported"
  179 | _Static_assert(CHECK_POWER_OF_2(SPI_TIMING_CORE_CLOCK_MHZ / SPI_TIMING_PSRAM_MODULE_CLOCK), "FLASH and PSRAM Mode configuration are not supported");
      | ^~~~~~~~~~~~~~
```

This is what I’ve done:
- checked out esp-idf from Github
- `git checkout v5.0` (I previously had v5.1.1 but the patch installer failed so I went back)
- Checked out SenseCAP_Indicator_ESP32, current master branch, commit 459fb0b8de1b8c823385e5185b5fdb482aed80c9.
- `cd path/to/esp_idf`
- Ran the patch install script from this repo
- Re-ran `install.sh`
- Re-ran `export.sh`
- `cd path/to/SenseCAP_Indicator_ESP32/examples/indicator_basis`
- `idf.py build`

Here’s the git status of the `esp-idf` directory, showing the modified files:
```
HEAD detached at v5.0
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   components/esp_hw_support/port/esp32s3/rtc_clk.c
	modified:   components/esp_psram/esp32s3/Kconfig.spiram
	modified:   components/hal/esp32s3/include/hal/spimem_flash_ll.h
	modified:   components/spi_flash/esp32s3/mspi_timing_tuning_configs.h
	modified:   components/spi_flash/esp32s3/spi_timing_config.c
	modified:   components/spi_flash/esp32s3/spi_timing_config.h
	modified:   components/spi_flash/spi_flash_timing_tuning.c

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	tools/test_apps/system/flash_psram/sdkconfig.ci.f8r8_120ddr
	tools/test_apps/system/flash_psram/sdkconfig.ci.f8r8_120ddr_120ddr

no changes added to commit (use "git add" and/or "git commit -a")
```

## Environment

- MacBook Pro 16” 2021 (M1 Pro)
- macOS 13.5.2

**Comment by snej** [comment]
I’ve worked around the problem by copying over the config files from the indicator_ha demo:
```sh
cp ../indicator_ha/sdkconfig* .
```

**Comment by Love4yzp** [comment]
Have you tried deleting the `build` folder and `sdkconfig` file?

**Comment by Love4yzp** [comment]
If there is no problem, I'd close the comment. same as #2
