### ISSUE TITLE
esp-library problem

### ISSUE THREAD

**Issue by ugurakas** [Seeed-Solution/SenseCAP_Indicator_ESP32#28]
I use sensecap indicator d1pro, I tried some of your examples, they work fine after installing esp-idf 5.0 and completing the patch file but after that I could not run the esp example on my computer. After completing your installation requirements,
I don't understand why I couldn't use any esp-idf samples in your products and other developer kits after initialization.
I don't understand where am I wrong, please help me.

**Comment by Love4yzp** [comment]
Could you show me some logs?

**Comment by ugurakas** [comment]
^~~~~~~~~~~~~~~~~~~        
C:/Users/ugura/esp/esp-idf-v5.0/components/iot_button/button_adc.c:181:5: note: in expansion of macro 'ESP_LOGV'        
  181 |     
ESP_LOGV(TAG, "Raw: %d\tVoltage: %dmV", adc_reading, voltage);
      |     
^~~~~~~~    
C:/Users/ugura/esp/esp-idf-v5.0/components/log/include/esp_log.h:265:27 
 error: format '%d' expects argument of type 'int', but argument 7 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]  
  265 | #define LOG_COLOR(COLOR)  "\033[0;" COLOR "m"       
      |                 
          ^~~~~~~~~     
C:/Users/ugura/esp/esp-idf-v5.0/components/log/include/esp_log.h:270:27 
 note: in expansion of macro 'LOG_COLOR'        
  270 | #define LOG_COLOR_I       LOG_COLOR(LOG_COLOR_GREEN)
      |                 
          ^~~~~~~~~     
C:/Users/ugura/esp/esp-idf-v5.0/components/log/include/esp_log.h:282:37 
 note: in expansion of macro 'LOG_COLOR_I'      
  282 | #define LOG_FORMAT(letter, format)  LOG_COLOR_ ## letter #letter " (%" PRIu32 ") %s: " format LOG_RESET_COLOR "\n"
      |                 
            
        ^~~~~~~~~~      
C:/Users/ugura/esp/esp-idf-v5.0/components/log/include/esp_log.h:414:86 
 note: in expansion of macro 'LOG_FORMAT'       
  414 |         else                
            
    { esp_log_write(ESP_LOG_INFO,       tag, LOG_FORMAT(I, format), esp_log_timestamp(), tag, ##__VA_ARGS__); } \       
      |                 
            
            
            
            
            
         ^~~~~~~~~~     
C:/Users/ugura/esp/esp-idf-v5.0/components/log/include/esp_log.h:432:41 
 note: in expansion of macro 'ESP_LOG_LEVEL'    
  432 |         if ( LOG_LOCAL_LEVEL >= level ) 
ESP_LOG_LEVEL(level, tag, format, ##__VA_ARGS__); \
      |                 
            

^~~~~~~~~~~~~
C:/Users/ugura/esp/esp-idf-v5.0/components/log/include/esp_log.h:344:38 
 note: in expansion of macro 'ESP_LOG_LEVEL_LOCAL'
  344 | #define ESP_LOGV( tag, format, ... ) ESP_LOG_LEVEL_LOCAL(ESP_LOG_VERBOSE, tag, format, ##__VA_ARGS__)
      |                 
            
         ^~~~~~~~~~~~~~~~~~~        
C:/Users/ugura/esp/esp-idf-v5.0/components/iot_button/button_adc.c:181:5: note: in expansion of macro 'ESP_LOGV'        
  181 |     
ESP_LOGV(TAG, "Raw: %d\tVoltage: %dmV", adc_reading, voltage);
      |     
^~~~~~~~    
cc1.exe: some warnings being treated as errors  
[16/....obj 
ninja: build stopped: subcommand failed.        

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command ninja " terminated with exit code: 1.

**Comment by Love4yzp** [comment]
@ugurakas The error is occurring because there is a mismatch between the format specifier and data type at line 181 in `button_adc.c`. 

Specifically:

- `ESP_LOGV` macro expands to `ESP_LOG_LEVEL` 
- `ESP_LOG_LEVEL` uses `LOG_FORMAT` macro
- `LOG_FORMAT` expects matching types between format specifiers and additional arguments
- At line 181, format `%d` expects `int` but `adc_reading` is `uint32_t`

This causes the format mismatch error. The compiler is treating this as an error due to the flags set. 

To fix, you should:

- Use `%u` format specifier for `uint32_t` type of `adc_reading`
- Or cast `adc_reading` to `int` before passing to `ESP_LOGV`
