### ISSUE TITLE
Tutorial for D1S Graphics Library Fails Compile.

### ISSUE THREAD

**Issue by rmeyer137** [Seeed-Solution/SenseCAP_Indicator_ESP32#57]
Following the tutorial from here:  https://wiki.seeedstudio.com/SenseCAP_Indicator_ESP32_Arduino/ it tells you to download the GFX_Library_for_Arduino from here: https://files.seeedstudio.com/wiki/wiki-ranger/Contributions/Indicator-Arduino/Arduino_GFX-master.zip

But I get an error when compiling. It gives the error: 
In file included from C:\Users\Rick\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_GFX_Library.h:4,
                 from C:\Users\Rick\AppData\Local\Temp\.arduinoIDE-unsaved2024613-5764-vaogl7.ghc5\SI_displaysensordata\SI_displaysensordata.ino:21:
C:\Users\Rick\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_DataBus.h:171:13: error: 'i80_device_list' has not been declared
  171 |   LIST_HEAD(i80_device_list, lcd_panel_io_i80_t)
      |             ^~~~~~~~~~~~~~~
C:\Users\Rick\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_DataBus.h:171:3: error: ISO C++ forbids declaration of 'LIST_HEAD' with no type [-fpermissive]
  171 |   LIST_HEAD(i80_device_list, lcd_panel_io_i80_t)
      |   ^~~~~~~~~
C:\Users\Rick\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_DataBus.h:171:48: error: expected ';' at end of member declaration
  171 |   LIST_HEAD(i80_device_list, lcd_panel_io_i80_t)
      |                                                ^
      |                                                 ;
C:\Users\Rick\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_DataBus.h:172:3: error: 'device_list' does not name a type
  172 |   device_list; // Head of i80 device list
      |   ^~~~~~~~~~~
C:\Users\Rick\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_DataBus.h:206:3: error: ISO C++ forbids declaration of 'LIST_ENTRY' with no type [-fpermissive]
  206 |   LIST_ENTRY(lcd_panel_io_i80_t)
      |   ^~~~~~~~~~
C:\Users\Rick\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_DataBus.h:206:32: error: expected ';' at end of member declaration
  206 |   LIST_ENTRY(lcd_panel_io_i80_t)
      |                                ^
      |                                 ;
C:\Users\Rick\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_DataBus.h:207:3: error: 'device_list_entry' does not name a type
  207 |   device_list_entry; // Entry of i80 device list
      |   ^~~~~~~~~~~~~~~~~
In file included from C:\Users\Rick\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_GFX_Library.h:19:
C:\Users\Rick\Documents\Arduino\libraries\GFX_Library_for_Arduino\src/databus/Arduino_ESP32RGBPanel.h:43:3: error: 'esp_lcd_rgb_panel_frame_trans_done_cb_t' does not name a type; did you mean 'esp_lcd_panel_io_color_trans_done_cb_t'?
   43 |   esp_lcd_rgb_panel_frame_trans_done_cb_t on_frame_trans_done; // Callback, invoked after frame trans done
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   esp_lcd_panel_io_color_trans_done_cb_t

exit status 1

**Comment by Love4yzp** [comment]
Do you have the skill to use esp-idf ?

**Comment by rmeyer137** [comment]
Yes I do.  Need to know what libraries and board I should be using for it.

Cheers,
Rick Meyer
Blog: https://missedallsigns.blogspot.com/

177 Union Street
Woodstock, NB
E7M 2W7
506-425-0357 Cell

This email and any attachments or links contained in it may be confidential
and are intended solely for the use of the individual to whom it is
addressed and may be subject to additional non-disclosure agreements. Any
views or opinions expressed are solely those of the author. If you are not
the intended recipient of this email, you must neither take any action
based on its contents nor copy or show it to anyone. Please contact the
sender if you believe you have received this email in error.

**Comment by Love4yzp** [comment]
Check out this diagram:
![image](https://github.com/user-attachments/assets/2a7295a8-d261-404f-a003-a8d059ff8102)

for flexible programming, we assume user to program on this way:
```
ESP-IDF -> ESP32S3 (Display, wireless layer)
Arduino -> RP2040 (Data capture layer)
```
details in [Wiki](https://wiki.seeedstudio.com/SenseCAP_Indicator_How_To_Flash_The_Default_Firmware)


As this repo is not open for Arduino, I'll close this issue, you can reopen at any time or ask for need on Discord.
