### ISSUE TITLE
Getting Started With Home Assistant demo code

### ISSUE THREAD

**Issue by Love4yzp** [Seeed-Solution/SenseCAP_Indicator_ESP32#8]

**Comment by jackyckygit** [comment]
please provide more information about using the PSRAM Octal 120 MHz feature in the **release/v5.0.2** branch of ESP-IDF or other newer release? cannot figure out how to config it.

**Comment by Love4yzp** [comment]
> please provide more information about using the PSRAM Octal 120 MHz feature in the **release/v5.0.2** branch of ESP-IDF or other newer release? cannot figure out how to config it.

We didn't test it in release/v5.0.2, you could start a discussion and log your problems.
once you patch it, you don't need to do anything, if you modify the file as 'sdkconfig`, you may delete it, to use the `sdkconfig.defaults`.

Thank you for your understanding.
